### ISSUE TITLE
Proposal: Nomad backend

### ISSUE THREAD

**Issue by adrianlop** [alexellis/faas-netes#17]
Hi, is there any plan to add Nomad support?
Thanks

**Comment by alexellis** [comment]
Hi @adrianlop It's not on the OpenFaaS roadmap - but If the community would like to implement it I'm happy to provide guidance.

**Comment by nicholasjackson** [comment]
Would love to build a Nomad plugin, going to hack on a prototype this weekend.

**Comment by alexellis** [comment]
Sounds great!

The other thing you might need to do is to write some sort of definition file for Nomad for the initial stack. There are two variants - the one which also includes NATS Streaming (for async) and the one which does not.

So you should be able to just "run" the API Gateway, Prometheus etc within a Nomad cluster without changes - as long as the services are reachable by DNS name. That's how we did it with K8s.

**Comment by nicholasjackson** [comment]
Awesome, I have started a scaffold project at: https://github.com/nicholasjackson/faas-nomad
will hack more on this tonight.

**Comment by alexellis** [comment]
Derek add label: skill/advanced

**Comment by alexellis** [comment]
@adrianlop did you want to sync up with @nicholasjackson - there is an implementation underway at: https://github.com/hashicorp/faas-nomad

**Comment by alexellis** [comment]
Closing this issue and redirecting to - https://github.com/alexellis/faas/issues/168
